disabled_rules:
  - line_length
excluded:
  - Pods
opt_in_rules:
  - array_init
  - contains_over_first_not_nil
  - vertical_whitespace
  - empty_count
  - switch_case_on_newline
  - overridden_super_call
  - explicit_init
  - conditional_returns_on_newline
  - closure_spacing
  - first_where
  - closure_end_indentation
  - attributes
  - implicit_return
  - object_literal
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - discouraged_direct_init
  - private_over_fileprivate
  - fatal_error_message
  - force_unwrapping
  - joined_default_parameter
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - override_in_extension
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - single_test_class
  - sorted_first_last
  - sorted_imports

# Rule configurations
identifier_name:
  excluded:
    - id
    - ok
    - to
    - ml # mililiter
    - x
    - y
    - z

# Disable errors, allow only warnings
cyclomatic_complexity:
  warning: 10
type_name:
  max_length: 50
force_cast: warning
force_try: warning
function_parameter_count: 5
large_tuple:
  warning: 3
  error: 4
