#$schema: https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Futured Engineering Handbook
site_url: https://futuredapp.github.io/Engineering-Handbook
theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/logo.svg

  font:
    text: Space Grotesk
    code: JetBrains Mono

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - toc.integrate
    - content.code.copy

plugins:
  - search

copyright: Made with ❤️‍🔥 at Futured

extra:
  social:
    - icon: material/web
      name: Web
      link: https://www.futured.app
    - icon: fontawesome/brands/github
      name: GitHub
      link: https://www.github.com/futuredapp
    - icon: fontawesome/brands/linkedin
      name: LinkedIn
      link: https://www.linkedin.com/company/futuredapps
    - icon: fontawesome/brands/instagram
      name: Instagram
      link: https://www.instagram.com/futuredapps

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
