#$schema: https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Futured Engineering Handbook
site_url: https://futuredapp.github.io/Engineering-Handbook
theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/logo.svg

  font:
    text: Space Grotesk
    code: JetBrains Mono

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to auto mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - content.code.copy

plugins:
  - search
  - glightbox:
      background: light-dark(white, black)
      shadow: false

nav:
  - Home: index.md
  - Teams:
      - Android & KMP:
          - Overview: Teams/android/index.md
          - Architecture:
              - Android-native: Teams/android/architecture/00_native.md
              - Kotlin Multiplatform: Teams/android/architecture/10_kmp.md
          - Project Setup:
              - First Steps: Teams/android/project_setup/00_new_repo.md
              - GitHub: Teams/android/project_setup/10_github.md
              - Project: Teams/android/project_setup/20_project.md
              - Firebase: Teams/android/project_setup/30_firebase.md
              - CI/CD: Teams/android/project_setup/40_ci_cd.md
          - Development:
              - Git Flow: Teams/android/development/00_git_flow.md
              - Code Style: Teams/android/development/10_code_style.md
              - Build Distribution: Teams/android/development/20_build_distrubution.md
          - Release:
              - Google Play: Teams/android/release/00_google_play.md
      - iOS:
          - Overview: Teams/iOS/index.md
          - New project: Teams/iOS/ios_new_project.md
          - Customer Account: Teams/iOS/ios_customer_account.md
          - Builds: Teams/iOS/ios_builds.md
          - Release: Teams/iOS/ios_release.md
    # - Design:
    #   - Overview: Teams/Design/design_page.md
    # - QA:
    #   - Overview: Teams/QA/qa_page.md
  - Editors: editors.md

copyright: Made with ❤️‍🔥 at Futured

extra:
  social:
    - icon: material/web
      name: Web
      link: https://www.futured.app
    - icon: fontawesome/brands/github
      name: GitHub
      link: https://www.github.com/futuredapp
    - icon: fontawesome/brands/linkedin
      name: LinkedIn
      link: https://www.linkedin.com/company/futuredapps
    - icon: fontawesome/brands/instagram
      name: Instagram
      link: https://www.instagram.com/futuredapps

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.caption
