#$schema: https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Futured Engineering Handbook
site_url: https://futuredapp.github.io/Engineering-Handbook
theme:
  name: material
  language: en

  custom_dir: docs/overrides

  icon:
    logo: futured/logo
    
  favicon: assets/favicon.svg

  font:
    code: JetBrains Mono

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to auto mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - content.code.copy

plugins:
  - search
  - glightbox:
      background: light-dark(white, black)
      shadow: false

nav:
  - Home: index.md
  - Android & KMP:
    - Overview: teams/android/index.md
    - Architecture:
        - Android-native: teams/android/architecture/00_native.md
        - Kotlin Multiplatform: teams/android/architecture/10_kmp.md
    - Project Setup:
        - First Steps: teams/android/project_setup/00_new_repo.md
        - GitHub: teams/android/project_setup/10_github.md
        - Project: teams/android/project_setup/20_project.md
        - Firebase: teams/android/project_setup/30_firebase.md
        - CI/CD: teams/android/project_setup/40_ci_cd.md
        - Translations: teams/android/project_setup/50_translations.md
    - Development:
        - Git Flow: teams/android/development/00_git_flow.md
        - Code Style: teams/android/development/10_code_style.md
        - Build Distribution: teams/android/development/20_build_distrubution.md
    - Release:
        - Google Play Account: teams/android/release/00_google_play_account.md
        - Google Play App: teams/android/release/10_google_play_app.md
        - CI/CD: teams/android/release/20_ci_cd.md
        - Process Overview: teams/android/release/30_release_process.md
  - iOS:
      - Overview: teams/ios/index.md
      - Architecture: teams/ios/ios_architecture.md
      - New Project: teams/ios/ios_new_project.md
      - Git Flow: teams/ios/ios_git_flow.md
      - Customer Account: teams/ios/ios_customer_account.md
      - Builds: teams/ios/ios_builds.md
      - Release: teams/ios/ios_release.md
      - CI/CD: teams/ios/ios_ci_cd.md
  - Full-stack:
      - Overview: teams/fullstack/index.md
      - Introduction:
          - Mission & Values: teams/fullstack/intro/00_mission.md
      - Development:
          - Git Flow: teams/fullstack/development/00_git_flow.md
          - Pull Request Guidelines: teams/fullstack/development/10_pull_request_guidelines.md
          - Code Review Process: teams/fullstack/development/20_code_review_process.md
          - Project Setup: teams/fullstack/development/30_project_setup.md
      - Tech Stack:
          - Frontend: teams/fullstack/tech_stack/00_frontend.md
          - Backend: teams/fullstack/tech_stack/10_backend.md
          - Database: teams/fullstack/tech_stack/20_database.md
          - DevOps: teams/fullstack/tech_stack/30_devops.md
          - Integrations: teams/fullstack/tech_stack/40_integrations.md
      - Coding Standards:
          - Style Guides: teams/fullstack/coding_standards/00_style_guides.md
          - Linting: teams/fullstack/coding_standards/10_linting.md
          - Secure Coding: teams/fullstack/coding_standards/20_secure_coding.md
          - Testing: teams/fullstack/coding_standards/30_testing.md
          - Error Handling: teams/fullstack/coding_standards/40_error_handling.md
      - Development Environment:
          - Local Setup: teams/fullstack/dev_env/00_local_setup.md
          - Tools: teams/fullstack/dev_env/10_tools.md
          - Secrets: teams/fullstack/dev_env/20_secrets.md
          - Troubleshooting: teams/fullstack/dev_env/30_troubleshooting.md
      - Deployment:
          - Process: teams/fullstack/deployment/00_deployment.md
          - Rollback: teams/fullstack/deployment/10_rollback.md
          - Monitoring: teams/fullstack/deployment/20_monitoring.md
          - Incidents: teams/fullstack/deployment/30_incidents.md
      - Documentation:
          - Code Documentation: teams/fullstack/docs/00_code_docs.md
          - API Documentation: teams/fullstack/docs/10_api_docs.md
      - Architecture:
          - Diagrams: teams/fullstack/architecture/00_diagrams.md
          - Decisions: teams/fullstack/architecture/10_decisions.md
          - Patterns: teams/fullstack/architecture/20_patterns.md
          - Scalability: teams/fullstack/architecture/30_scalability.md
      - Security:
          - Authentication: teams/fullstack/security/00_auth.md
          - Privacy: teams/fullstack/security/10_privacy.md
          - Dependencies: teams/fullstack/security/20_dependencies.md
          - Vulnerabilities: teams/fullstack/security/30_vulnerabilities.md
      - Quality Assurance:
          - Testing Strategy: teams/fullstack/qa/00_testing_strategy.md
          - Testing: teams/fullstack/qa/10_testing.md
          - Checklist: teams/fullstack/qa/20_checklist.md
      - Continuous Improvement:
          - Retrospectives: teams/fullstack/improvement/00_retrospectives.md
          - Technical Debt: teams/fullstack/improvement/10_technical_debt.md
          - Experimentation: teams/fullstack/improvement/20_experimentation.md
      - Learning:
          - Reading: teams/fullstack/learning/00_reading.md
          - Tech Talks: teams/fullstack/learning/10_tech_talks.md
      - Appendices:
          - Glossary: teams/fullstack/appendices/00_glossary.md
          - Scripts: teams/fullstack/appendices/10_scripts.md
          - FAQ: teams/fullstack/appendices/20_faq.md
          - Templates: teams/fullstack/appendices/30_templates.md

    # - Design:
    #   - Overview: teams/design/design_page.md
    # - QA:
    #   - Overview: teams/qa/qa_page.md
  - Contributing: editors.md

copyright: Made with ❤️‍🔥 at Futured

extra:
  social:
    - icon: material/web
      name: Web
      link: https://www.futured.app
    - icon: fontawesome/brands/github
      name: GitHub
      link: https://www.github.com/futuredapp
    - icon: fontawesome/brands/linkedin
      name: LinkedIn
      link: https://www.linkedin.com/company/futuredapps
    - icon: fontawesome/brands/instagram
      name: Instagram
      link: https://www.instagram.com/futuredapps

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.caption
